// Generated by Rec Studio 4 - build Jun  2 2014

_init(
    _unknown_ __ebx                        // r1
)
{// addr = 0x08048370
    _unknown_ _t2;                         // _t2
    intOrPtr _t4;                          // _t4
    _unknown_ _t5;                         // _t5

    _t5 = __ebx;
    __x86.get_pc_thunk.bx(_t2);
    _t4 =  *((intOrPtr*)(_t5 + 0x1c83));
    if(_t4 != 0) {
        __gmon_start__();
        return _t4;
    }
    return _t4;
}

int printf(char* format)
{// addr = 0x080483B0
    goto __imp__printf;
}

int fflush(struct _IO_FILE* fp)
{// addr = 0x080483C0
    goto __imp__fflush;
}

char* gets(char* dst)
{// addr = 0x080483D0
    goto __imp__gets;
}

int system(char* __command)
{// addr = 0x080483E0
    goto __imp__system;
}

__gmon_start__()
{// addr = 0x080483F0
    goto __imp____gmon_start__;
}

void srand(int __seed)
{// addr = 0x08048400
    goto __imp__srand;
}

__libc_start_main()
{// addr = 0x08048410
    goto __imp____libc_start_main;
}

int rand()
{// addr = 0x08048420
    goto __imp__rand;
}

_start(
    _unknown_ __eax,                       // r0
    _unknown_ __edx                        // r3
)
{// addr = 0x08048430
    __edx = __edx;
    __eax = __eax;
    _pop(__esi);
    __ecx = __esp;
    __esp = __esp & 240;
    _push(__eax);
    _push(__esp);
    _push(__edx);
    _push(__libc_csu_fini);
    _push(__libc_csu_init);
    _push(__ecx);
    _push(__esi);
    _push(main);
    __libc_start_main();
    asm("hlt ");
    asm("o16 nop ");
    asm("o16 nop ");
    asm("o16 nop ");
    asm("o16 nop ");
    asm("o16 nop ");
    asm("o16 nop ");
    asm("o16 nop ");
    return __eax;
}

__x86.get_pc_thunk.bx(
    _unknown_ __eax                        // r0
)
{// addr = 0x08048460
    __eax = __eax;
    return __eax;
}

give_shell()
{// addr = 0x08048535
    signed int _v16;                       // _cfa_fffffff0
    _unknown_ __ebp;                       // r6
    intOrPtr _t13;                         // _t13

    _v16 = 0;
    while(_v16 <= 4) {
        _t13 =  *((intOrPtr*)(_v16 * 4 +  &rands));
        if( *((intOrPtr*)(_v16 * 4 +  &nums)) == _t13) {
            _v16 = _v16 + 1;
            continue;
        }
        return _t13;
    }
    return system("/bin/sh");
}

f1()
{// addr = 0x08048576
    _unknown_ __ebp;                       // r6

    __eax = rands;
    nums = __eax;
    return __eax;
}

f2()
{// addr = 0x08048585
    _unknown_ __ebp;                       // r6

    __eax =  *134520928;
     *134520908 = __eax;
    return __eax;
}

f3()
{// addr = 0x08048594
    _unknown_ __ebp;                       // r6

    __eax =  *134520932;
     *134520912 = __eax;
    return __eax;
}

f4()
{// addr = 0x080485A3
    _unknown_ __ebp;                       // r6

    __eax =  *134520936;
     *134520916 = __eax;
    return __eax;
}

f5()
{// addr = 0x080485B2
    _unknown_ __ebp;                       // r6

    __eax =  *134520940;
     *134520920 = __eax;
    return __eax;
}

name()
{// addr = 0x080485C1
    char _v112;                            // _cfa_ffffff90
    _unknown_ __ebp;                       // r6

    printf("Enter your name ");
    fflush(__imp__stdout);
    gets( &_v112);
    return  &_v112;
}

main(
    intOrPtr _a4,                          // _cfa_4
    intOrPtr _a8                           // _cfa_8
)
{// addr = 0x080485F3
    signed int _v8;                        // _cfa_fffffff8
    signed int _v12;                       // _cfa_fffffff4
    intOrPtr _v16;                         // _cfa_fffffff0
    intOrPtr _v32;                         // _cfa_ffffffe0
    _unknown_ __ebp;                       // r6

    __esp = __esp & 240;
    __esp = __esp - 32;
    _v12 =  *((intOrPtr*)( *((intOrPtr*)(_a8 + 0 + (_a4 + 1073741823) * 4))));
    srand(_v12 * 2942913);
    _v8 = 0;
    while(_v8 <= 4) {
         *(_v8 * 4 +  &rands) = rand();
        _v8 = _v8 + 1;
    }
    _v16 = name();
    _v32 = _v16;
    printf("Your name is %s\n");
    return give_shell();
}

__libc_csu_init(
    _unknown_ __ebx,                       // r1
    intOrPtr _a4,                          // _cfa_4
    intOrPtr _a8,                          // _cfa_8
    intOrPtr _a12                          // _cfa_c
)
{// addr = 0x08048680
    intOrPtr _v36;                         // _cfa_ffffffdc
    intOrPtr _v40;                         // _cfa_ffffffd8
    signed int __edi;                      // r4
    _unknown_ __esi;                       // r5
    intOrPtr __ebp;                        // r6
    _unknown_ _t12;                        // _t12
    _unknown_ _t17;                        // _t17
    _unknown_ _t18;                        // _t18
    signed int _t21;                       // _t21
    signed int _t22;                       // _t22

    _t17 = __ebx;
    __edi = 0;
    __x86.get_pc_thunk.bx(_t12);
    _t18 = _t17 + 6517;
    __esp = __esp - 28;
    __ebp = _a4;
    _init(_t18);
    _t21 = _t18 + -244 - _t18 + -248 >> 2;
    if(_t21 != 0) {
        _t22 = _t21;
        do {
             *__esp = __ebp;
            _v36 = _a12;
            _v40 = _a8;
             *((intOrPtr*)(_t18 + -248 + __edi * 4))();
            __edi = __edi + 1;
        } while(__edi != _t22);
    }
    __esp = __esp + 28;
    return;
}

__libc_csu_fini(
    _unknown_ __eax                        // r0
)
{// addr = 0x080486F0
    __eax = __eax;
    return __eax;
}

_fini(
    _unknown_ __ebx                        // r1
)
{// addr = 0x080486F4
    _unknown_ _t1;                         // _t1

    return __x86.get_pc_thunk.bx(_t1);
}

_fini(
    _unknown_ __ebx                        // r1
)
{// addr = 0x080486F4
    _unknown_ _t1;                         // _t1

    return @rec __x86.get_pc_thunk.bx@__x86.get_pc_thunk.bx@(_t1);
}

// Statistics:
//      54 Register nodes
//      24 Temporaries nodes
//       6 Casts
//     198 Statements
//       0 Labels
//       0 Gotos
//      22 Blocks
//     347 Nodes
//       8 Assembly nodes
//      22 Unknown Types


Total time: 0 seconds.
