/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2014 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

int init_proc();
// int puts(const char *s);
// size_t strlen(const char *s);
// int __gmon_start__(void); weak
// void *malloc(size_t size);
// int __fastcall __isoc99_scanf(_QWORD, _QWORD); weak
int __cdecl main(int argc, const char **argv, const char **envp);
signed int deregister_tm_clones();
int register_tm_clones();
signed int _do_global_dtors_aux();
int frame_dummy();
// void *__usercall make_node@<rax>(char *s@<rdi>, int a2@<esi>, void *a3@<r14>);
__int64 __fastcall check(__int64 a1, __int64 a2);
void *__fastcall sol(__int64 a1);
__int64 __fastcall push(char a1);
__int64 pop();
int __fastcall _libc_csu_init(unsigned int a1, __int64 a2, __int64 a3);
void term_proc();

//-------------------------------------------------------------------------
// Data declarations

__int64 (__fastcall *_frame_dummy_init_array_entry[2])() = { &frame_dummy, &_do_global_dtors_aux }; // weak
__int64 (__fastcall *_do_global_dtors_aux_fini_array_entry)() = &_do_global_dtors_aux; // weak
int solution = 2; // weak
int dword_601264 = 3; // weak
int dword_601268 = 40; // weak
int dword_60126C = 8; // weak
int dword_601270 = 13; // weak
int dword_601274 = 0; // weak
int dword_601278 = 46; // weak
int dword_60127C = 13; // weak
int dword_601280 = 0; // weak
int dword_601284 = 23; // weak
int dword_601288 = 10; // weak
int dword_60128C = 49; // weak
int dword_601290 = 2; // weak
int dword_601294 = 46; // weak
char completed_6627; // weak
_BYTE stack[1024]; // idb
signed int stack_index[2]; // idb
// extern _UNKNOWN _gmon_start__; weak


//----- (00000000004004D0) ----------------------------------------------------
int init_proc()
{
  _UNKNOWN *v0; // rax@1

  v0 = &_gmon_start__;
  if ( &_gmon_start__ )
    LODWORD(v0) = __gmon_start__();
  return (signed int)v0;
}
// 400540: using guessed type int __gmon_start__(void);

//----- (0000000000400570) ----------------------------------------------------
int __cdecl main(int argc, const char **argv, const char **envp)
{
  void *v3; // r14@0
  void *v4; // r15@1
  void *v5; // rbx@1
  void *v6; // ST18_8@1
  void *v7; // ST10_8@1
  void *v8; // ST08_8@1
  void *v9; // ST00_8@1
  void *v10; // r14@1
  void *v11; // r12@1
  void *v12; // r13@1
  void *v13; // rbp@1
  void *v14; // rax@1
  char *v15; // rax@1
  char v16; // r8@1
  char v17; // cl@2
  const char *v18; // rax@7
  __int64 v19; // rdi@8
  char s; // [sp+20h] [bp-148h]@1
  __int64 v22; // [sp+128h] [bp-40h]@1

  v22 = *MK_FP(__FS__, 40LL);
  v4 = make_node("memory_corruption!", 1, v3);
  v5 = make_node("buffer_overflow!", 2, v3);
  v6 = make_node("return_oriented_programming!", 3, v3);
  v7 = make_node("do_you_remember_picoctf?", 4, v3);
  v8 = make_node("baleful_was_my_favorite_problem", 5, v3);
  make_node("not_a_forensice_challenge", 6, v3);
  make_node("your_flag_is_just_kidding_there_is_no_flag_here", 7, v3);
  make_node("did_you_know_that_ctf_is_more_fun_with_mips_assembly", 8, v3);
  v9 = make_node("lorem_ipsum_dolor_sit_amet_consecutor_idk_what_goes_here", 9, v3);
  v10 = make_node("lolnothingtoseehere", 0, v3);
  v11 = make_node("gosh_are_you_really_still_reading_these", 14, v10);
  v12 = make_node("k...", 1, v10);
  v13 = make_node("y u no play moar vvvvry spooky game", 2, v10);
  v14 = make_node("c is my favorite language", 4, v10);
  **((_QWORD **)v5 + 1) = v6;
  **((_QWORD **)v6 + 1) = v8;
  **((_QWORD **)v8 + 1) = v7;
  **((_QWORD **)v7 + 1) = v9;
  **((_QWORD **)v9 + 1) = v4;
  **((_QWORD **)v4 + 1) = v10;
  **((_QWORD **)v10 + 1) = v12;
  **((_QWORD **)v12 + 1) = v11;
  **((_QWORD **)v11 + 1) = v13;
  *(_QWORD *)v13 = v14;
  __isoc99_scanf("%s", &s);
  LODWORD(v15) = puts(&s);
  v16 = *((_BYTE *)v5 + 16);
  if ( v16 & 0xDF )
  {
    v17 = s;
    v15 = &s;
    if ( s )
    {
      while ( 1 )
      {
        v5 = *(void **)v5;
        ++v15;
        if ( !(*((_BYTE *)v5 + 16) & 0xDF) )
          break;
        v17 = *v15;
        v16 = *((_BYTE *)v5 + 16);
        if ( !*v15 )
          goto LABEL_8;
      }
      if ( v17 == v16 )
      {
        v18 = (const char *)sol((__int64)&s);
        LODWORD(v15) = puts(v18);
      }
    }
  }
LABEL_8:
  v19 = *MK_FP(__FS__, 40LL) ^ v22;
  return (signed int)v15;
}
// 400560: using guessed type int __fastcall __isoc99_scanf(_QWORD, _QWORD);

//----- (00000000004007C0) ----------------------------------------------------
signed int deregister_tm_clones()
{
  return 7;
}

//----- (0000000000400800) ----------------------------------------------------
int register_tm_clones()
{
  return 0;
}

//----- (0000000000400840) ----------------------------------------------------
signed int _do_global_dtors_aux()
{
  signed int result; // eax@2

  if ( !completed_6627 )
  {
    result = deregister_tm_clones();
    completed_6627 = 1;
  }
  return result;
}
// 6012C0: using guessed type char completed_6627;

//----- (0000000000400860) ----------------------------------------------------
int frame_dummy()
{
  return register_tm_clones();
}
// 400860: could not find valid save-restore pair for rbp

//----- (0000000000400890) ----------------------------------------------------
void *__usercall make_node@<rax>(char *s@<rdi>, int a2@<esi>, void *a3@<r14>)
{
  char *v3; // r15@1
  void *v4; // rbp@1
  __int64 v5; // rbx@2
  int v6; // er13@2
  void *v7; // rax@4
  char v8; // dl@4
  void *v9; // rsi@4
  void *result; // rax@5
  int v11; // [sp+4h] [bp-44h]@1

  v3 = s;
  v4 = malloc(0x18uLL);
  v11 = strlen(s);
  if ( v11 <= 0 )
  {
    v9 = v4;
    result = v4;
  }
  else
  {
    v5 = a2;
    a3 = v4;
    v6 = 0;
    while ( 1 )
    {
      v7 = malloc(0x18uLL);
      v6 += v5;
      v8 = *v3;
      v3 += v5++;
      v9 = v7;
      *(_QWORD *)a3 = v7;
      *((_BYTE *)a3 + 16) = v8;
      if ( v11 <= v6 )
        break;
      a3 = v7;
    }
    result = v4;
  }
  *((_BYTE *)v9 + 16) = 0;
  *((_QWORD *)result + 1) = a3;
  return result;
}

//----- (0000000000400930) ----------------------------------------------------
__int64 __fastcall check(__int64 a1, __int64 a2)
{
  char v2; // cl@1
  char v3; // dl@2
  __int64 result; // rax@6

  v2 = *(_BYTE *)(a1 + 16);
  if ( v2 & 0xDF && (v3 = *(_BYTE *)a2) != 0 )
  {
    while ( 1 )
    {
      a1 = *(_QWORD *)a1;
      ++a2;
      if ( !(*(_BYTE *)(a1 + 16) & 0xDF) )
        break;
      v3 = *(_BYTE *)a2;
      v2 = *(_BYTE *)(a1 + 16);
      if ( !*(_BYTE *)a2 )
        goto LABEL_7;
    }
    result = v2 == v3;
  }
  else
  {
LABEL_7:
    result = 0LL;
  }
  return result;
}

//----- (0000000000400980) ----------------------------------------------------
void *__fastcall sol(__int64 a1)
{
  void *result; // rax@1
  __int64 v2; // rdx@1

  result = malloc(0x40uLL);
  *(_BYTE *)result = *(_BYTE *)(a1 + solution);
  *((_BYTE *)result + 1) = *(_BYTE *)(a1 + dword_601264);
  *((_BYTE *)result + 2) = *(_BYTE *)(a1 + dword_601268);
  *((_BYTE *)result + 3) = *(_BYTE *)(a1 + dword_60126C);
  *((_BYTE *)result + 4) = *(_BYTE *)(a1 + dword_601270);
  *((_BYTE *)result + 5) = *(_BYTE *)(a1 + dword_601274);
  *((_BYTE *)result + 6) = *(_BYTE *)(a1 + dword_601278);
  *((_BYTE *)result + 7) = *(_BYTE *)(a1 + dword_60127C);
  *((_BYTE *)result + 8) = *(_BYTE *)(a1 + dword_601280);
  *((_BYTE *)result + 9) = *(_BYTE *)(a1 + dword_601284);
  *((_BYTE *)result + 10) = *(_BYTE *)(a1 + dword_601288);
  v2 = dword_60128C;
  *((_BYTE *)result + 15) = 0;
  *((_BYTE *)result + 11) = *(_BYTE *)(a1 + v2);
  *((_BYTE *)result + 12) = *(_BYTE *)(a1 + dword_601290);
  *((_BYTE *)result + 13) = *(_BYTE *)(a1 + dword_601294);
  return result;
}
// 601260: using guessed type int solution;
// 601264: using guessed type int dword_601264;
// 601268: using guessed type int dword_601268;
// 60126C: using guessed type int dword_60126C;
// 601270: using guessed type int dword_601270;
// 601274: using guessed type int dword_601274;
// 601278: using guessed type int dword_601278;
// 60127C: using guessed type int dword_60127C;
// 601280: using guessed type int dword_601280;
// 601284: using guessed type int dword_601284;
// 601288: using guessed type int dword_601288;
// 60128C: using guessed type int dword_60128C;
// 601290: using guessed type int dword_601290;
// 601294: using guessed type int dword_601294;

//----- (0000000000400A60) ----------------------------------------------------
__int64 __fastcall push(char a1)
{
  __int64 result; // rax@1

  result = stack_index[0];
  ++stack_index[0];
  stack[result] = a1;
  return result;
}

//----- (0000000000400A80) ----------------------------------------------------
__int64 pop()
{
  --stack_index[0];
  return stack[stack_index[0]];
}

//----- (0000000000400AA0) ----------------------------------------------------
int __fastcall _libc_csu_init(unsigned int a1, __int64 a2, __int64 a3)
{
  __int64 v3; // r13@1
  __int64 v4; // rbx@1
  signed __int64 v5; // rbp@1
  int result; // eax@1

  v3 = a3;
  v4 = 0LL;
  v5 = &_do_global_dtors_aux_fini_array_entry - _frame_dummy_init_array_entry;
  result = init_proc();
  if ( v5 )
  {
    do
      result = ((int (__fastcall *)(_QWORD, __int64, __int64))_frame_dummy_init_array_entry[v4++])(a1, a2, v3);
    while ( v4 != v5 );
  }
  return result;
}
// 601000: using guessed type __int64 (__fastcall *_frame_dummy_init_array_entry[2])();
// 601008: using guessed type __int64 (__fastcall *_do_global_dtors_aux_fini_array_entry)();

//----- (0000000000400B14) ----------------------------------------------------
void term_proc()
{
  ;
}

// ALL OK, 13 function(s) have been successfully decompiled
